| # | Change Item                                            | Description                                                                                                                                                     | Status |
| - | ------------------------------------------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------ |
| 1 | **Add Port Validation to Case A**                      | Add a third condition to Case A: <br>**“Ports allowed are within 1024–65535.”**                                                                                 | ☐      |
| 2 | **Clarify “All Conditions Must Be Met” in Case A**     | Add introductory text above Case A: <br>*“Approve only if all of the following conditions are met:”*                                                            | ☐      |
| 3 | **Refine Terminology in Case A - Point 2**             | Update wording to be precise: <br>*“All sources are either non-prod DIDs, NDS, or collections that only contain non-prod assets.”*                              | ☐      |
| 4 | **Scope Clarification for Pattern Page**               | At the top or in a note, clarify that the document applies only to **production** Atlas setup. <br>*“This pattern applies to production Atlas setups only.”*    | ☐      |
| 5 | **Review Case B for Duplication**                      | Validate that none of the 6 conditions in Case B are already handled/enforced elsewhere. If yes, add notes like: <br>*“(Already enforced via \[tool/process])”* | ☐      |
| 6 | **Note Lack of Enforcement for Classification Parity** | Where DP/Privacy classification conditions are stated (e.g., point 4/5), add: <br>*“This is not currently enforced and must be manually validated.”*            | ☐      |
| 7 | **Review and Clean Up Questionnaire to Kishore**       | Remove any questions that are already documented in the pattern page. Keep only real gaps.                                                                      | ☐      |
